### ISSUE TITLE
All defined routes return 404

### ISSUE THREAD

**Issue by raldred** [BackendStack21/fast-gateway#64]
**Describe the bug**
Please forgive my ignorance if I've missed something completely obvious here.
I'm just trying to run a very simple gateway based off your basic demo and all of the routes return 404.

<details>
  <summary>My example server.js</summary>

  ```
  'use strict'
  
  const gateway = require('fast-gateway')
  const PORT = process.env.PORT || 8080
  
  gateway({
    routes: [{
      prefix: '/public',
      target: 'http://localhost:3000'
      /*
      // applicable in case Swagger Definitions would be supported on downstream service
      docs: {
        name: 'Public Service',
        endpoint: 'swagger.json',
        type: 'swagger'
      }
      */
    }, {
      prefix: '/admin',
      target: 'http://localhost:3001'
    }, {
      // this route definition makes http://localhost:3000 (/public) a default service if other routes prefixes are omitted
      prefix: '/*',
      target: 'http://localhost:3000'
    }]
  }).start(PORT).then(server => {
    console.log(`API Gateway listening on ${PORT} port!`)
  })
  
  const service1 = require('restana')({})
  service1
    .get('/hi', (req, res) => res.send('Hello World!'))
    .get('/hi-chunked', (req, res) => {
      res.write('Hello ')
      res.write('World!')
      res.end()
    })
    .start(3000).then(() => console.log('Public service listening on 3000 port!'))
  
  const service2 = require('restana')({})
  service2
    .get('/users', (req, res) => res.send([]))
    .start(3001).then(() => console.log('Admin service listening on 3001 port!'))
  ```
</details>

I'm using
Node version: 14.15.3
Npm version: 7.5.3
MacOS 11.2

**To Reproduce**
Copy the server.js file above.
run `node server.js`
I see the startup output fine

```
API Gateway listening on 8080 port!
Public service listening on 3000 port!
Admin service listening on 3001 port!
```

I've checked lsof and the servers are running and listening:
![image](https://user-images.githubusercontent.com/37096/117485617-7afc2c00-af60-11eb-8144-c02405ec9b9d.png)

I hit `/services.json`
and I get the routes outputting
![image](https://user-images.githubusercontent.com/37096/117484607-391eb600-af5f-11eb-9330-273f4038e6bb.png)

If I hit any other route on the gateway I get nothing

![image](https://user-images.githubusercontent.com/37096/117484470-0379cd00-af5f-11eb-9cb6-34d129191364.png)
![image](https://user-images.githubusercontent.com/37096/117484697-5a7fa200-af5f-11eb-9736-6252418d4b1c.png)

If I hit the targets directly eg.
`http://localhost:3000/hi` or `http://localhost:3001/users` I get `Hello World!` and `[]` respectively.

**Expected behavior**  
I'd expect the defined routes to return the various responses from the targets.

**Desktop (please complete the following information):**  
 - OS: MacOS 11.2
 - Browser chrome & safari tried
 - Version 90

**Additional context**  
Node version: 14.15.3
Npm version: 7.5.3

**Comment by jkyberneees** [comment]
Hi @raldred, thanks for reaching out. Why are you using `pathRegex: ''`. Can you try without it?

Regards

**Comment by raldred** [comment]
Hey @jkyberneees yeh not sure, i think i was just trying stuff, the basic demo has it it for the catch all route.
Evening with it the only route that works is `/services.json`

I've updated the example im using with the pathPrefix removed

**Comment by jkyberneees** [comment]
Hi @raldred, please have a look at this example: https://github.com/BackendStack21/fast-gateway/blob/master/demos/basic.js.

You can try: 
- curl http://localhost:8080/public/hi
- curl http://localhost:8080/admin/users
- curl http://localhost:8080/hi

**Comment by itajenglish** [comment]
@jkyberneees What if I want to match my endpoints exactly? For example, I want `/v1/users` defined in the gateway to forward the request exactly like that to the API that has a route defined the same way `v1/users`
