### ISSUE TITLE
support for formdata

### ISSUE THREAD

**Issue by HoaX7** [BackendStack21/fast-gateway#67]
I wasn't able to forward formdata with or without files.

i also tried express parser with restana, that also didnt work.,.

**Comment by jkyberneees** [comment]
Hi @HoaX7, fast-proxy will forward low level requests as well. Are you using the body-parser middleware?
This is a custom middleware I have used in the past to support multi-part requests:

```js
const reqType = require('type-is')

  (req, res, next) => {
    if (!reqType.hasBody(req)) {
      req.headers['content-length'] = '0'
      req.body = undefined
    } else if (req.headers['content-type'] && req.headers['content-type'].startsWith('multipart/form-data')) {
      // proxy raw upload requests to downstream service
      req.body = undefined
    }
    next()
  }

```

Regards

**Comment by HoaX7** [comment]
Yeah I just took the raw body and passed it to my service manually. I did it in a ugly way for time sake, I'll see if I can leverage using the snippet you provided me.
