### ISSUE TITLE
Query parameter serialization changes style

### ISSUE THREAD

**Issue by sPaCeMoNk3yIam** [BackendStack21/fast-gateway#80]
When using a specific query [parameter serialization style](https://swagger.io/docs/specification/serialization/) it might be this lib changes the serialization for the upstream request.
https://github.com/BackendStack21/fast-gateway/blob/4a2ff7d02aedc3157413145040bc7fd115070660/index.js#L121

This actually stores the _parsed_ query params to `queryString` rather than the original string. Then for `'http'` proxy type's `fast-proxy-lite` uses it's default serialization, which is comma separated:
https://github.com/BackendStack21/fast-proxy-lite/blob/eb9df39341a33591e2aee596d69e5aed8256561e/index.js#L141

Imho it'd be better to use the original query string - over the parsed one - to make sure no change happens. Otherwise, an easy option to specify the serialization style would be a good alternative - maybe in addition for a serialization callback (enum | function).

The above mentioned line of code could be changed to `require('url').parse(req.url, false).query` or `require('url').parse(req.url, true).search` - depending on if the leading `?` needs to be included or not.

**Comment by raoulus** [comment]
👍
