### ISSUE TITLE
CORS Implemetation

### ISSUE THREAD

**Issue by nilayupadhyay17** [BackendStack21/fast-gateway#91]
How to implement CORS with fast-gateway?

**Comment by jkyberneees** [comment]
Hi @nilayupadhyay17 , you can use middlewares like https://www.npmjs.com/package/cors connected to global or route level middlewares.

Regards

**Comment by nilayupadhyay17** [comment]
@jkyberneees thanks for your reply. I  want to enable cors on global level with fast-gateway but not really sure how to use cors middleware that you've mentioned. If you can give an example or something, then it would be really helpful. 

I would like to do something as below.

var express = require('express')
var cors = require('cors')
var app = express()
 
app.use(cors())
 
app.get('/products/:id', function (req, res, next) {
  res.json({msg: 'This is CORS-enabled for all origins!'})
})
 
app.listen(80, function () {
  console.log('CORS-enabled web server listening on port 80')
})

thanks in advance!

**Comment by nilayupadhyay17** [comment]
thank you @jkyberneees !
